# Default values for namesilo-dyndns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: grapemix/namesilo-dyndns
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1"

fullnameOverride: "namesilo-dyndns"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 10m
    memory: 16Mi
  requests:
    cpu: 10m
    memory: 16Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
 
env:
  # -- Timezone for the container.
  - name: TZ
    value: UTC
  - name: PRINT_SAME_COUNT_STEP
    value: 360

cronJob:
  # -- Create a cron job to update the DNS zone.
  enabled: false
  # -- Update schedule for the cron job.
  schedule: '30 * * * *'
  # -- Enable/disable the cron job schedule quickly.
  suspend: false
  # -- The number of successful finished jobs to retain.
  successfulJobsHistoryLimit: 3
  # -- The number of failed finished jobs to retain.
  failedJobsHistoryLimit: 1
  # -- The nameservers used to resolve ip service domain. Leave empty to inherit from cluster/node.
  nameservers: []
  # -- Additional annotations for the cronjob object.
  annotations: {}
  # -- Additional labels for the cronjob object.
  labels: {}

secret:
  # -- Create a new secret containing the token.
  create: true
  # -- Use an existing secret to store the token.
  existingSecret: ''
  # -- Token used when not using an existing secret.
  token: ''
  # -- Additional annotations for the secret object.
  annotations: {}
  # -- Additional labels for the secret object.
  labels: {}

nodeSelector: {}

tolerations: []

affinity: {}
